global:
  url: "www.evaluatemessage.dev"

prometheus:
  server:
    baseURL: "http://localhost:80/prometheus"
    extraArgs:
      web.route-prefix: "/"
grafana:
  persistence:
    enabled: true
  grafana.ini:
    server:
      root_url: 'http://localhost:3000/grafana/'
      serve_from_sub_path: true