apiVersion: cloud.google.com/v1
kind: BackendConfig
metadata:
  name: {{ include "istio.name" .}}-backend-config
  namespace: {{ .Release.Namespace }}
  annotations:
    {{ .Values.ingress.annotations | toYaml | nindent 4 }}
spec:
  healthCheck:
    type: HTTP
    requestPath: /healthz/ready
    port: 15021