apiVersion: cloud.google.com/v1
kind: BackendConfig
metadata:
  name: {{ include "istio.name" .}}-backend-config
  namespace: {{ .Release.Namespace }}
  annotations:
    {{ .Values.ingress.annotations | toYaml | nindent 4 }}
spec:
  healthCheck:
    checkIntervalSec: 30
    timeoutSec: 5
    healthyThreshold: 1
    unhealthyThreshold: 2
    type: HTTP
    requestPath: /healthz/ready
    port: 15021