apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "istio.name" .}}
  namespace: {{ .Release.Namespace }}
  annotations:
    {{ .Values.ingress.annotations | toYaml | nindent 4 }}
    kubernetes.io/ingress.global-static-ip-name: {{ .Values.ingress.staticIpName }}
    networking.gke.io/managed-certificates: {{ include "istio.name" .}}-managed-cert
    networking.gke.io/v1beta1.FrontendConfig: {{ include "istio.name" .}}-frontend-config
    kubernetes.io/ingress.class: "gce"
spec:
  rules:
    - host: {{ .Values.ingress.domain }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ .Values.gateway.name }}
                port:
                  number: 443