apiVersion: networking.gke.io/v1
kind: ManagedCertificate
metadata:
  name: {{ include "istio.name" .}}-managed-cert
  namespace: {{ .Release.Namespace }}
  annotations:
    {{ .Values.ingress.annotations | toYaml | nindent 4 }}
spec:
  domains:
    - {{ .Values.ingress.domain }}