ingress:
  domain: "www.evaluatemessage.dev"
  staticIpName: "istio-ingress-ip"
  annotations:
    "helm.sh/hook": post-install
    "helm.sh/hook-weight": "5"
    
gateway:
  name: "istio-ingressgateway"
  annotations:
    "helm.sh/hook": post-install
    "helm.sh/hook-weight": "1"
  service:
    type: ClusterIP
    annotations: 
      "cloud.google.com/neg": '{"ingress": true}'
      "cloud.google.com/backend-config": '{"ports": {"http":"istio-backend-config"}}'