apiVersion: cloud.google.com/v1
kind: BackendConfig
metadata:
  name: {{ include "metric.name" .}}-backend-config
  namespace: {{ .Release.Namespace }}
spec:
  healthCheck:
    type: HTTP
    requestPath: /healthz/ready
    port: 15021