apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: grafana-vs
  namespace: {{ .Release.Namespace }}
spec:
  hosts:
  - "*"
  gateways:
  - metric-gateway
  http:
  - match:
    - uri:
        exact: /grafana
    - uri:
        prefix: /grafana
    - uri:
        prefix: /grafana/
    route:
    - destination:
        host: {{ include "metric.name" . }}-grafana.{{ .Release.Namespace }}.svc.cluster.local
        port:
          number: 80
