apiVersion: networking.gke.io/v1
kind: ManagedCertificate
metadata:
  name: {{ include "metric.name" .}}-managed-cert
  namespace: {{ .Release.Namespace }}
spec:
  domains:
    - {{ .Values.ingress.domain }}