apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: prometheus-vs
  namespace: {{ .Release.Namespace }}
spec:
  hosts:
  - "*"
  gateways:
  - metric-gateway
  http:
  - match:
    - uri:
        exact: /prometheus
    - uri:
        prefix: /prometheus/
    rewrite:
      uri: "/"
    route:
    - destination:
        host: {{ include "metric.name" . }}-prometheus-server.{{ .Release.Namespace }}.svc.cluster.local
        port:
          number: 80
